---
kind: pipeline
type: exec
name: exec run bun on linux amd64

platform:
  os: linux
  arch: amd64

steps:
- name: greet
  commands:
  - ls -a
  - uname -a
  - echo $PATH
- export BUN_INSTALL="$HOME/.bun"
- export PATH=$BUN_INSTALL/bin:$PATH
  - echo $PATH
  - bun run bunTest.ts

---
kind: pipeline
type: exec
name: exec run bun on darwin arm64

platform:
  os: darwin
  arch: arm64

steps:
- name: greet
  commands:
  - ls -a
  - uname -a
  - echo $SHELL
  - echo $PATH
  - cat ~/.bashrc
- export BUN_INSTALL="$HOME/.bun"
- export PATH=$BUN_INSTALL/bin:$PATH
  - echo $PATH
  - bun run bunTest.ts

--- 
kind: pipeline
type: ssh
name: ssh test on linux arm64

platform:
  os: linux
  arch: arm64

server: 
  host: 
    from_secret: host_bytedance_shanghai_1
  user: root
  password:
    from_secret: passwd_bytedance_shanghai_1
  
steps:
- name: greeting
  commands:
  - ls -a
  - uname -a
  - echo $PATH
- export BUN_INSTALL="$HOME/.bun"
- export PATH=$BUN_INSTALL/bin:$PATH
  - echo $PATH
  - bun run bunTest.ts

--- 
kind: pipeline
type: ssh
name: ssh test on linux amd64

platform:
  os: linux
  arch: amd64

server: 
  host: 
    from_secret: host_bytedance_shanghai_1
  user: root
  password:
    from_secret: passwd_bytedance_shanghai_1
  
steps:
- name: greeting
  commands:
  - ls -a
  - uname -a
  - echo $PATH
- export BUN_INSTALL="$HOME/.bun"
- export PATH=$BUN_INSTALL/bin:$PATH
  - echo $PATH
  - bun run bunTest.ts

# should differ node runner.




# ---
# kind: pipeline
# type: exec
# name: exec run bun on linux arm64

# platform:
#   os: linux
#   arch: arm64

# steps:
# - name: greet
#   commands:
#   - echo hello from shell
#   - echo $SHELL
#   - ls -a
#   - volta ls
#   - bun run bunTest.ts



# --------------------------------------------- No Environment Below

# ---
# kind: pipeline
# type: exec
# # exec runner not support darwin arm64?
# name: exec run bun on darwin amd64

# platform:
#   os: darwin
#   arch: amd64

# steps:
# - name: greet
#   commands:
#   - echo hello from shell
#   - whoami
#   - pwd
#   - uname -a
#   - echo $SHELL
#   - volta ls
#   - bun run bunTest.ts

# --------------------------------------------- No Environment Above





# ----------------------------------------------- OK Part below

# ---
# kind: pipeline
# type: docker
# name: docker run bun on linux amd64

# platform:
#   os: linux
#   arch: amd64

# steps:
# - name: run ts file
#   image: oven/bun
#   commands:
#   - bun bunTest.ts

# ---
# kind: pipeline
# type: docker
# name: docker run bun on linux arm64

# platform:
# # docker runner unable use platform darwin?
#   os: linux
#   arch: arm64

# steps:
# - name: run ts file
#   image: oven/bun
#   commands:
#   - bun bunTest.ts

# ------------------------------------------------ OK part upward