---
kind: pipeline
type: exec
name: exec run bun on linux amd64

platform:
  os: linux
  arch: amd64

steps:
- name: greet
  commands:
  - echo hello from shell
  - whoami
  - pwd
  - uname -a
  - volta ls
  - volta ls
  - bun run bunTest.ts

---
kind: pipeline
type: exec
name: exec run bun on linux arm64

platform:
  os: linux
  arch: arm64

steps:
- name: greet
  commands:
  - echo hello from shell
  - volta ls
  - bun run bunTest.ts

---
kind: pipeline
type: exec
name: exec run bun on darwin arm64

platform:
  os: darwin
  arch: arm64

steps:
- name: greet
  commands:
  - echo hello from shell
  - whoami
  - pwd
  - uname -a
  - volta ls
  - volta ls
  - bun run bunTest.ts

---
kind: pipeline
type: exec
# exec runner not support darwin arm64?
name: exec run bun on darwin amd64

platform:
  os: darwin
  arch: arm64

steps:
- name: greet
  commands:
  - echo hello from shell
  - whoami
  - pwd
  - uname -a
  - volta ls
  - bun run bunTest.ts









# ----------------------------------------------- OK Part below

# ---
# kind: pipeline
# type: docker
# name: docker run bun on linux amd64

# platform:
#   os: linux
#   arch: amd64

# steps:
# - name: run ts file
#   image: oven/bun
#   commands:
#   - bun bunTest.ts

# ---
# kind: pipeline
# type: docker
# name: docker run bun on linux arm64

# platform:
# # docker runner unable use platform darwin?
#   os: linux
#   arch: arm64

# steps:
# - name: run ts file
#   image: oven/bun
#   commands:
#   - bun bunTest.ts

# ------------------------------------------------ OK part upward